# -*- coding: utf-8 -*-
"""assignment2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/arkuzaytepe/assignment2.c7f600e7-d4e7-4621-a63c-9683e2aded91.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20251105/auto/storage/goog4_request%26X-Goog-Date%3D20251105T103055Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D09f4fc49ea5cace424d7b833b90a8787cdb4cd6d8173c2926baefdca8e3c2d6e68dd6771ed7ee20621654ec0b30b44b796d72763eef88f61f6a45a0073be1bb74d21e0dafbe73748bd669d02f939a863dd2894e1da0225a9f0d83eff5d0763cf1ccabe528c0f8770142ce01d1726aa5f57129e0f757b3c15cab4c52aee86b0e55b2e797f58bba9d88d9905356323e02ac32958ecd0e767c902ba45b7cb498ba60ee73e1a03eb4a1bc6f26b3b96009f45884a1119e4e4d8962a90baaf44d7a1d56a500ffcd52978e077c20f37012b666c6047c2109986ed15f9e4421b43359485b4cc9746b1d3bf5dc9c578f05398919ed98f84fa536921f75a0fb17e9e244c0a
"""

# IMPORTANT: SOME KAGGLE D,,,,,,,,,2ATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

arkuzaytepe_pa2_data_path = kagglehub.dataset_download('arkuzaytepe/pa2-data')

print('Data source import complete.')

# Commented out IPython magic to ensure Python compatibility.
# Commented out IPython magic to ensure Python compatibility.
# %pip install "opencv-contrib-python" "numpy==1.26.4"

# -*- coding: utf-8 -*-
"""
Hücre 1: Kütüphaneler ve Görselleştirme Yardımcı Fonksiyonları (v2 - DÜZELTİLMİŞ)
"""
import cv2
import numpy as np
import matplotlib.pyplot as plt
import os
import random
import time
import pandas as pd

# %matplotlib inline

print("Kütüphaneler başarıyla yüklendi.")
print(f"OpenCV Versiyonu: {cv2.__version__}")
print(f"NumPy Versiyonu: {np.__version__}")
print(f"Pandas Versiyonu: {pd.__version__}")


# --- YENİ: Rapor için Görselleştirme Fonksiyonları ---

def save_and_show_keypoints(image, keypoints, path, title="Keypoints"):
    """
    Anahtar noktaları çizer, kaydeder ve gösterir.
    """
    img_bgr = image.copy()
    if len(img_bgr.shape) == 2:
        img_bgr = cv2.cvtColor(img_bgr, cv2.COLOR_GRAY2BGR)

    vis = cv2.drawKeypoints(img_bgr, keypoints, None, flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
    cv2.imwrite(path, vis)

    print(f"Görsel kaydedildi: {path}")
    plt.figure(figsize=(10, 7))
    plt.imshow(cv2.cvtColor(vis, cv2.COLOR_BGR2RGB))
    plt.title(title)
    plt.axis('off')
    plt.show()

def save_and_show_matches(img1, kp1, img2, kp2, matches, path, title="Matches"):
    """
    Eşleşmeleri çizer, kaydeder ve gösterir.
    """
    vis = cv2.drawMatches(img1, kp1, img2, kp2, matches, None, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)
    cv2.imwrite(path, vis)

    print(f"Görsel kaydedildi: {path}")
    plt.figure(figsize=(15, 8))
    plt.imshow(cv2.cvtColor(vis, cv2.COLOR_BGR2RGB))
    plt.title(title)
    plt.axis('off')
    plt.show()

def save_and_show_inliers_outliers(img1, kp1, img2, kp2, good_matches, inlier_mask, path, title="Inliers (Yeşil) vs Outliers (Kırmızı)"):
    """
    Inlier ve Outlier eşleşmelerini farklı renklerde çizer.
    """
    dmatches = [m for m in good_matches]

    # --- HATA BURADAYDI (İKİNCİ DÜZELTME) ---
    # ÖNCEKİ (HATALI):
    # matches_mask = inlier_mask.astype(np.uint8).reshape(-1, 1).tolist()
    # HATA: Bu, [[1], [0], [1]] gibi bir liste üretiyordu.

    # DÜZELTİLMİŞ (DOĞRU):
    # .reshape(-1, 1) kaldırıldı. Düz bir liste [1, 0, 1] olmalı.
    matches_mask = inlier_mask.astype(np.uint8).tolist()
    # ------------------------

    # Inlier'ları yeşil, Outlier'ları kırmızı çiz
    vis = cv2.drawMatches(
        img1, kp1, img2, kp2, dmatches, None,
        matchColor=(0, 255, 0),     # Inlier rengi (Yeşil)
        singlePointColor=(0, 0, 255), # Outlier rengi (Kırmızı)
        matchesMask=matches_mask,
        flags=cv2.DrawMatchesFlags_DEFAULT
    )

    cv2.imwrite(path, vis)
    print(f"Görsel kaydedildi: {path}")
    plt.figure(figsize=(15, 8))
    plt.imshow(cv2.cvtColor(vis, cv2.COLOR_BGR2RGB))
    plt.title(title)
    plt.axis('off')
    plt.show()

print("\nHücre 1 (v2 - DÜZELTİLMİŞ) tanımlandı.")

# -*- coding: utf-8 -*-
"""
Hücre 2: Temel Algoritma Fonksiyonları
"""

def extract_features(image, method='sift'):
    """
    Verilen görüntüden anahtar noktaları ve tanımlayıcıları çıkarır.
    PDF [cite: 34] SIFT, SURF, ve ORB yöntemlerini ister.
    """
    if method.lower() == 'sift':
        detector = cv2.SIFT_create()
    elif method.lower() == 'surf':
        try:
            # Bu, opencv-contrib-python gerektirir
            detector = cv2.xfeatures2d.SURF_create()
        except AttributeError:
            print("SURF'u kullanmak için 'opencv-contrib-python' paketini kurun.")
            print("SIFT'a geri dönülüyor...")
            detector = cv2.SIFT_create()
    elif method.lower() == 'orb':
        detector = cv2.ORB_create(nfeatures=2000)
    else:
        raise ValueError("Desteklenmeyen metot. 'sift', 'surf' veya 'orb' kullanın.")

    keypoints, descriptors = detector.detectAndCompute(image, None)
    return keypoints, descriptors

def match_features(des1, des2, method='sift', ratio_thresh=0.75):
    """
    İki tanımlayıcı setini eşleştirir ve Lowe's ratio test uygular[cite: 39].
    """
    if method.lower() in ['sift', 'surf']:
        # SIFT/SURF için NORM_L2
        bf = cv2.BFMatcher(cv2.NORM_L2, crossCheck=False)
    else: # ORB için NORM_HAMMING
        bf = cv2.BFMatcher(cv2.NORM_HAMMING, crossCheck=False)

    # k=2, her bir tanımlayıcı için en iyi 2 eşleşmeyi bulur
    matches = bf.knnMatch(des1, des2, k=2)

    good_matches = []
    # 'matches' listesindeki her bir öğe (m, n) çifti içerir
    for m, n in matches:
        # m: en iyi eşleşme, n: ikinci en iyi eşleşme
        if m.distance < ratio_thresh * n.distance:
            good_matches.append(m)

    return good_matches

def normalize_points(points):
    """
    Noktaları DLT'nin sayısal kararlılığı için normalleştirir[cite: 51].
    """
    centroid = np.mean(points, axis=0)
    mean_dist = np.mean(np.linalg.norm(points - centroid, axis=1))

    if mean_dist < 1e-8:
        scale = 1.0
    else:
        scale = np.sqrt(2) / mean_dist

    T = np.array([
        [scale, 0, -scale * centroid[0]],
        [0, scale, -scale * centroid[1]],
        [0, 0, 1]
    ])

    points_hom = np.hstack((points, np.ones((points.shape[0], 1))))
    normalized_points_hom = (T @ points_hom.T).T

    normalized_points_hom_z = normalized_points_hom[:, 2]
    # Sıfıra bölmeyi önle
    normalized_points_hom_z[np.abs(normalized_points_hom_z) < 1e-8] = 1.0

    normalized_points = normalized_points_hom[:, :2] / normalized_points_hom_z[:, np.newaxis]

    return normalized_points, T

def compute_homography_dlt(src_pts, dst_pts):
    """
    4 veya daha fazla noktadan DLT kullanarak homografi hesaplar[cite: 46, 50].
    Bu, cv2.findHomography() KULLANILMAYAN manuel implementasyondur[cite: 48].
    """
    if src_pts.shape[0] < 4: return None

    A = []
    for i in range(src_pts.shape[0]):
        x, y = src_pts[i]; u, v = dst_pts[i]
        # DLT denklemleri
        A.extend([
            [-x, -y, -1, 0, 0, 0, u*x, u*y, u],
            [0, 0, 0, -x, -y, -1, v*x, v*y, v]
        ])

    A = np.asarray(A)
    # SVD çözümü
    _, _, Vh = np.linalg.svd(A)

    # Homografi vektörü h, Vh'nin son satırıdır
    last_element = Vh[-1, -1]
    if abs(last_element) < 1e-8: return None # Geçersiz çözüm

    h = Vh[-1, :] / last_element
    return h.reshape(3, 3)

print("Hücre 2 (Temel Fonksiyonlar) tanımlandı.")

# -*- coding: utf-8 -*-
"""
Hücre 3: DÜZELTİLMİŞ RANSAC Fonksiyonu
"""

def compute_homography_ransac_upgraded(src_pts, dst_pts, iterations=1000, threshold=5.0):
    """
    RANSAC uygular (manuel implementasyon).
    YENİ: Inlier/Outlier görselleştirmesi için 'inlier_mask' ve
    rapor tablosu için 'reprojection_error' döndürür.
    """
    max_inliers = 0
    best_H = None
    best_inlier_mask = None # Indeksler yerine maske
    n_points = len(src_pts)

    if n_points < 4:
        return None, None, None

    # Tüm noktaları homojen koordinatlara çevir (döngü dışında bir kez)
    src_pts_hom = np.hstack((src_pts, np.ones((n_points, 1))))

    for _ in range(iterations):
        # 1. Rastgele 4 nokta seç
        indices = random.sample(range(n_points), 4)

        # 2. Bu 4 noktayı NORMALLEŞTİR
        src_sample, T_src = normalize_points(src_pts[indices])
        dst_sample, T_dst = normalize_points(dst_pts[indices])

        # 3. Normalleştirilmiş noktalara DLT uygula
        H_norm = compute_homography_dlt(src_sample, dst_sample)
        if H_norm is None: continue

        # 4. Homografiyi "geri normalleştir" (un-normalize)
        H_candidate = np.linalg.inv(T_dst) @ H_norm @ T_src
        if np.any(np.isnan(H_candidate)): continue

        # 5. Tüm noktaları kullanarak inlier'ları bul
        transformed_pts_hom = (H_candidate @ src_pts_hom.T).T

        # Sıfıra bölme hatalarını önle
        z = transformed_pts_hom[:, 2]
        z[np.abs(z) < 1e-8] = 1.0 # Geçersizleri 1 yap
        transformed_pts = transformed_pts_hom[:, :2] / z[:, np.newaxis]

        # Yeniden projeksiyon hatasını (reprojection error) TÜM noktalar için hesapla
        errors = np.linalg.norm(dst_pts - transformed_pts, axis=1)

        # YENİ: Indeksler yerine boolean maske kullan
        current_inlier_mask = (errors < threshold)
        current_inlier_count = np.sum(current_inlier_mask)

        # 6. En iyi modeli sakla
        if current_inlier_count > max_inliers:
            max_inliers = current_inlier_count
            best_inlier_mask = current_inlier_mask
            best_H = H_candidate # best_H'yi sakla, H_norm'u değil

    # 7. Tüm inlier'ları kullanarak homografiyi yeniden hesapla (daha stabil sonuç için)
    final_H = None
    mean_reprojection_error = None

    if best_inlier_mask is not None and max_inliers > 4:
        inlier_indices = np.where(best_inlier_mask)[0]

        # Yine normalizasyon kullanarak!

        # --- HATA BURADAYDI ---
        # ÖNCEKİ (HATALI):
        # src_inliers, T_src_final = normalize_points(src_pts[inlier_indices])
        # dst_inliers, T_dst_final = normalize_points(dst_pts[inlier_indices])

        # DÜZELTİLMİŞ (DOĞRU):
        src_inliers_norm, T_src_final = normalize_points(src_pts[inlier_indices])
        dst_inliers_norm, T_dst_final = normalize_points(dst_pts[inlier_indices])
        # ------------------------

        # H_norm_final = compute_homography_dlt(src_inliers_norm, dst_inliers_norm)
        # Yukarıdaki düzeltme ile bu satır artık doğru çalışacak:
        H_norm_final = compute_homography_dlt(src_inliers_norm, dst_inliers_norm)

        if H_norm_final is not None:
            final_H = np.linalg.inv(T_dst_final) @ H_norm_final @ T_src_final

            # YENİ: Sadece inlier'lar üzerindeki ortalama hatayı raporla
            inliers_hom = src_pts_hom[inlier_indices]
            transformed_inliers_hom = (final_H @ inliers_hom.T).T
            z_inliers = transformed_inliers_hom[:, 2]
            z_inliers[np.abs(z_inliers) < 1e-8] = 1.0
            transformed_inliers = transformed_inliers_hom[:, :2] / z_inliers[:, np.newaxis]

            inlier_errors = np.linalg.norm(dst_pts[inlier_indices] - transformed_inliers, axis=1)
            mean_reprojection_error = np.mean(inlier_errors)

    # best_inlier_mask, tüm 'good_matches' listesiyle aynı boyuttadır
    return final_H, best_inlier_mask, mean_reprojection_error

print("Hücre 3 (DÜZELTİLMİŞ RANSAC) tanımlandı.")

# -*- coding: utf-8 -*-
"""
Hücre 4: Güncellenmiş Panorama Oluşturma Fonksiyonu
"""

def create_panorama_with_intermediates(img1, img2, H):
    """
    İki görüntüyü birleştirir[cite: 57].
    YENİ: Rapor için ara görselleri döndürür.
    :return: (panorama, warped_img2, overlap_mask)
    """
    H = H.astype(np.float32)
    h1, w1 = img1.shape[:2]; h2, w2 = img2.shape[:2]

    # Tuvalin (canvas) boyutlarını hesapla
    corners2 = np.array([[0, 0], [0, h2], [w2, h2], [w2, 0]], dtype=np.float32).reshape(-1, 1, 2)
    transformed_corners = cv2.perspectiveTransform(corners2, H)
    corners1 = np.array([[0, 0], [0, h1], [w1, h1], [w1, 0]], dtype=np.float32).reshape(-1, 1, 2)
    all_corners = np.concatenate((corners1, transformed_corners), axis=0)

    x_min, y_min = np.int32(all_corners.min(axis=0).ravel())
    x_max, y_max = np.int32(all_corners.max(axis=0).ravel())

    # Görüntüleri pozitif koordinatlara kaydırmak için öteleme matrisi
    trans_dist = [-x_min, -y_min]
    H_trans = np.array([[1, 0, trans_dist[0]], [0, 1, trans_dist[1]], [0, 0, 1]], dtype=np.float32)

    width, height = x_max - x_min, y_max - y_min

    # 1. Çarpıtılmış görüntü (RAPORDA İSTENEN) [cite: 60, 134]
    warped_img2 = cv2.warpPerspective(img2, H_trans @ H, (width, height), borderValue=(0, 0, 0))

    # 2. Referans görüntüyü (img1) tuvale yerleştir
    panorama = np.zeros((height, width, 3), dtype=np.uint8)
    panorama[trans_dist[1]:h1+trans_dist[1], trans_dist[0]:w1+trans_dist[0]] = img1

    # 3. Birleştirme (Blending)
    mask_warped = np.any(warped_img2 > 0, axis=2)
    mask_pano = np.any(panorama > 0, axis=2)

    warped_only = mask_warped & ~mask_pano
    panorama[warped_only] = warped_img2[warped_only]

    # Çakışan alan (RAPORDA İSTENEN) [cite: 61, 134]
    overlap_mask = mask_warped & mask_pano

    # Basit ortalama (Simple averaging) veya doğrusal harmanlama (linear blending) [cite: 59]
    if np.any(overlap_mask):
        panorama[overlap_mask] = cv2.addWeighted(panorama[overlap_mask], 0.5, warped_img2[overlap_mask], 0.5, 0)

    # YENİ: Ara görselleri de döndür
    return panorama, warped_img2, overlap_mask

print("Hücre 4 (Güncellenmiş Panorama Oluşturma) tanımlandı.")

# -*- coding: utf-8 -*-
"""
Hücre 5: Ana Panorama İşleme ve Raporlama Döngüsü
"""

print("Panorama oluşturma ve rapor verisi toplama işlemi başlıyor...")

# LÜTFEN VERİ SETİ YOLUNU KONTROL EDİN
# Kaggle için: '/kaggle/input/assgnmentthesecond/panorama_dataset'
# Yerel makine için: 'panorama_dataset' (eğer kodla aynı dizindeyse)
base_panorama_path = '/kaggle/input/pa2-data/panorama_dataset'
output_dir = 'panorama_results' # [cite: 156]
visuals_dir = 'report_visuals' # Rapor görselleri için
os.makedirs(output_dir, exist_ok=True)
os.makedirs(visuals_dir, exist_ok=True)

try:
    scenes = [d for d in os.listdir(base_panorama_path) if os.path.isdir(os.path.join(base_panorama_path, d))]
    # Ödevde 6 sahne olduğu belirtiliyor [cite: 58]
    print(f"Toplam {len(scenes)} sahne bulundu: {scenes}")
except FileNotFoundError:
    print(f"HATA: '{base_panorama_path}' klasörü bulunamadı. Lütfen yolu güncelleyin.")
    scenes = []

# YENİ: Karşılaştırma tablosu için [cite: 137]
feature_methods = ['sift', 'surf', 'orb']
comparison_data = [] # Rapor tablosu için veriler
processed_scenes_for_visuals = set() # Her sahnenin görselini sadece 1 kez kaydetmek için

for scene in scenes:
    print(f"\n--- Sahne işleniyor: {scene} ---")
    scene_path = os.path.join(base_panorama_path, scene)

    # PDF'te [kaynak: 23] belirtildiği gibi 1.png ve 2.png kullanılır
    ref_image_path = os.path.join(scene_path, '1.png')
    target_image_path = os.path.join(scene_path, '2.png')

    if not os.path.exists(ref_image_path) or not os.path.exists(target_image_path):
        print(f"Uyarı: {scene} için 1.png veya 2.png bulunamadı, atlanıyor.")
        continue

    ref_image = cv2.imread(ref_image_path)
    target_image = cv2.imread(target_image_path)
    if ref_image is None or target_image is None:
        print(f"Uyarı: {scene} için görüntüler yüklenemedi, atlanıyor.")
        continue

    ref_gray = cv2.cvtColor(ref_image, cv2.COLOR_BGR2GRAY)
    target_gray = cv2.cvtColor(target_image, cv2.COLOR_BGR2GRAY)

    # YENİ: Tüm yöntemleri karşılaştır [cite: 137]
    for method in feature_methods:
        print(f"  -> Yöntem: {method.upper()}")
        try:
            # 1. Özellik Çıkarımı
            start_time_feat = time.time()
            kp_ref, des_ref = extract_features(ref_gray, method)
            kp_target, des_target = extract_features(target_gray, method)
            time_feat = time.time() - start_time_feat
            if des_ref is None or des_target is None or len(des_ref) < 10 or len(des_target) < 10:
                print("     Yetersiz özellik bulundu, atlanıyor.")
                continue

            # 2. Özellik Eşleştirme
            start_time_match = time.time()
            good_matches = match_features(des_ref, des_target, method=method)
            time_match = time.time() - start_time_match
            if len(good_matches) < 10:
                print("     Yetersiz eşleşme bulundu, atlanıyor.")
                continue

            # 3. Homografi (Güncellenmiş RANSAC ile)
            src_pts = np.float32([kp_ref[m.queryIdx].pt for m in good_matches]).reshape(-1, 2)
            dst_pts = np.float32([kp_target[m.trainIdx].pt for m in good_matches]).reshape(-1, 2)

            start_time_ransac = time.time()
            # RANSAC parametreleri [cite: 127]
            H, inlier_mask, reproj_err = compute_homography_ransac_upgraded(src_pts, dst_pts, iterations=2000, threshold=5.0)
            time_ransac = time.time() - start_time_ransac

            if H is None:
                print("     Homografi hesaplanamadı (yeterli inlier bulunamadı).")
                continue

            inlier_count = np.sum(inlier_mask)
            inlier_ratio = inlier_count / len(good_matches)

            # 4. Panorama ve Ara Görselleri Alma
            start_time_pano = time.time()
            panorama, warped_img, overlap_mask = create_panorama_with_intermediates(ref_image, target_image, H)
            time_pano = time.time() - start_time_pano

            output_path = os.path.join(output_dir, f"{scene}_{method}_panorama.png")
            cv2.imwrite(output_path, panorama)
            print(f"     Başarılı: Panorama kaydedildi. Inliers: {inlier_count}/{len(good_matches)} ({inlier_ratio:.2%})")

            # 5. YENİ: Rapor tablosu için veri topla [cite: 137]
            total_time = time_feat + time_match + time_ransac + time_pano
            comparison_data.append({
                'Sahne': scene, 'Yöntem': method,
                'KP (Ref)': len(kp_ref), 'KP (Tgt)': len(kp_target),
                'Eşleşme': len(good_matches), 'Inlier': inlier_count,
                'Inlier Oranı': inlier_ratio,
                'Hata (Reproj.)': reproj_err,
                'Süre (Toplam)': total_time
            })

            # 6. YENİ: Rapor görsellerini kaydet (her sahne için sadece bir kez) [cite: 131-134]
            if scene not in processed_scenes_for_visuals:
                print(f"     RAPOR GÖRSELLERİ '{visuals_dir}' klasörüne kaydediliyor...")
                vis_path_base = os.path.join(visuals_dir, f"{scene}_{method}")

                # Keypoints [cite: 131]
                save_and_show_keypoints(ref_image, kp_ref, f"{vis_path_base}_1_keypoints_ref.png", f"{scene} Keypoints (Ref)")

                # Matches (filtered) [cite: 132]
                save_and_show_matches(ref_image, kp_ref, target_image, kp_target, good_matches, f"{vis_path_base}_2_matches.png", f"{scene} Filtered Matches")

                # Inliers/Outliers [cite: 133]
                save_and_show_inliers_outliers(ref_image, kp_ref, target_image, kp_target, good_matches, inlier_mask, f"{vis_path_base}_3_inliers_outliers.png", f"{scene} Inliers vs Outliers")

                # Warping & Overlap [cite: 134]
                cv2.imwrite(f"{vis_path_base}_4_warped_target.png", warped_img)
                overlap_vis = (overlap_mask.astype(np.uint8) * 255)
                overlap_vis_color = cv2.cvtColor(overlap_vis, cv2.COLOR_GRAY2BGR)
                cv2.imwrite(f"{vis_path_base}_5_overlap_mask.png", overlap_vis_color)

                print(f"     Görsel kaydedildi: {vis_path_base}_4_warped_target.png")
                print(f"     Görsel kaydedildi: {vis_path_base}_5_overlap_mask.png")

                processed_scenes_for_visuals.add(scene) # Bu sahne için görseller tamam

        except Exception as e:
            print(f"     !!! {method} yönteminde beklenmedik HATA: {e}")
            # SURF için hata oluşursa (opencv-contrib-python yoksa)
            if method == 'surf':
                print("     SURF atlandı (muhtemelen 'opencv-contrib-python' eksik).")


print("\n\n" + "="*50)
print("Panorama Oluşturma Tamamlandı.")
print("="*50 + "\n")


# --- YENİ: BÖLÜM 1: SIFT/SURF/ORB Karşılaştırma Tablosu [cite: 137] ---
print("--- Karşılaştırma Tablosu (Rapor için) ---")
if comparison_data:
    comparison_df = pd.DataFrame(comparison_data)
    # Pandas ayarı: Tüm sütunları göster
    pd.set_option('display.max_rows', None)
    pd.set_option('display.max_columns', None)
    pd.set_option('display.width', 1000)
    print(comparison_df.to_string())
else:
    print("Karşılaştırma verisi oluşturulamadı (muhtemelen dosyalar bulunamadı).")

print("\n\n" + "="*50)


# --- YENİ: BÖLÜM 2: RANSAC Parametre Analizi (Ablation Study) [cite: 138] ---
print("--- RANSAC Ablation Study (Rapor için) ---")
# Test için ilk başarılı sahneyi ve SIFT'ı kullanalım
if comparison_data:
    # SIFT ile yapılan ilk başarılı denemeyi bul
    sift_data = [d for d in comparison_data if d['Yöntem'] == 'sift']
    if sift_data:
        test_scene = sift_data[0]['Sahne']
        print(f"Test Sahnesi: {test_scene} (Yöntem: SIFT)")

        # Verileri yeniden yükle
        ref_image = cv2.imread(os.path.join(base_panorama_path, test_scene, '1.png'))
        target_image = cv2.imread(os.path.join(base_panorama_path, test_scene, '2.png'))
        ref_gray = cv2.cvtColor(ref_image, cv2.COLOR_BGR2GRAY)
        target_gray = cv2.cvtColor(target_image, cv2.COLOR_BGR2GRAY)

        kp_ref_abl, des_ref_abl = extract_features(ref_gray, 'sift')
        kp_tgt_abl, des_tgt_abl = extract_features(target_gray, 'sift')
        good_matches_abl = match_features(des_ref_abl, des_tgt_abl, 'sift')
        src_pts_abl = np.float32([kp_ref_abl[m.queryIdx].pt for m in good_matches_abl]).reshape(-1, 2)
        dst_pts_abl = np.float32([kp_tgt_abl[m.trainIdx].pt for m in good_matches_abl]).reshape(-1, 2)

        # Test edilecek parametre setleri [cite: 138]
        abl_params = [
            {'iterations': 500, 'threshold': 5.0},
            {'iterations': 2000, 'threshold': 5.0}, # Orijinal
            {'iterations': 5000, 'threshold': 5.0},
            {'iterations': 2000, 'threshold': 1.0}, # Daha sıkı eşik
            {'iterations': 2000, 'threshold': 10.0}, # Daha gevşek eşik
        ]
        abl_results = []

        for params in abl_params:
            H, mask, err = compute_homography_ransac_upgraded(src_pts_abl, dst_pts_abl, **params)
            if H is not None:
                abl_results.append({
                    'İterasyon': params['iterations'],
                    'Eşik (Threshold)': params['threshold'],
                    'Inlier Sayısı': np.sum(mask),
                    'Inlier Oranı': np.sum(mask) / len(good_matches_abl),
                    'Hata (Reproj.)': err
                })

        abl_df = pd.DataFrame(abl_results)
        print(abl_df.to_string(index=False))
    else:
        print("Ablation study için SIFT verisi bulunamadı.")
else:
    print("Ablation study için veri bulunamadı.")

print("\n\nTüm panorama rapor verileri ve görselleri oluşturuldu.")

# -*- coding: utf-8 -*-
"""
Hücre 6: AR (Artırılmış Gerçeklik) Yardımcı Fonksiyonu (Crop)
"""

def crop_center(img, target_aspect_ratio):
    """
    Görüntüyü hedef en-boy oranına göre merkezden kırpar.
    """
    h, w = img.shape[:2]
    img_aspect = w / h

    if img_aspect > target_aspect_ratio:
        # Görüntü hedeften daha geniş, genişliği kırp
        new_w = int(target_aspect_ratio * h)
        offset = (w - new_w) // 2
        cropped_img = img[:, offset:offset + new_w]
    elif img_aspect < target_aspect_ratio:
        # Görüntü hedeften daha yüksek, yüksekliği kırp
        new_h = int(w / target_aspect_ratio)
        offset = (h - new_h) // 2
        cropped_img = img[offset:offset + new_h, :]
    else:
        # En-boy oranları zaten aynı
        cropped_img = img

    return cropped_img

print("Hücre 6 (AR Crop Fonksiyonu) tanımlandı.")

# -*- coding: utf-8 -*-
"""
Hücre 7: Ana AR (Artırılmış Gerçeklik) İşleme Döngüsü
"""

# LÜTFEN VERİ SETİ YOLUNU KONTROL EDİN
# Kaggle için: '/kaggle/input/assgnmentthesecond/ar_dataset'
# Yerel makine için: 'ar_data' (eğer kodla aynı dizindeyse)
ar_data_path = '/kaggle/input/pa2-data/ar_dataset'
book_video_path = os.path.join(ar_data_path, 'book.mov') # [cite: 76]
source_video_path = os.path.join(ar_data_path, 'ar_source.mov') # [cite: 78]
cover_image_path = os.path.join(ar_data_path, 'cv_cover.jpg') # [cite: 77]

# 1. Referans kapak görüntüsünü yükle ve özelliklerini çıkar (bu sadece bir kez yapılır)
cover_image = cv2.imread(cover_image_path)
if cover_image is None:
    print(f"HATA: Kapak görüntüsü '{cover_image_path}' yüklenemedi. AR kısmı çalıştırılamıyor.")
else:
    cover_gray = cv2.cvtColor(cover_image, cv2.COLOR_BGR2GRAY)
    kp_cover, des_cover = extract_features(cover_gray, 'sift') # SIFT genellikle en stabil olanıdır
    h_cover, w_cover = cover_image.shape[:2]
    # Kapağın en-boy oranı hesaplandı [cite: 90, 91]
    cover_aspect_ratio = w_cover / h_cover
    print(f"Referans kapak görüntüsü ({w_cover}x{h_cover}) yüklendi.")

    # 2. Video yakalama nesnelerini oluştur [cite: 82]
    cap_book = cv2.VideoCapture(book_video_path)
    cap_source = cv2.VideoCapture(source_video_path)

    if not cap_book.isOpened() or not cap_source.isOpened():
        print("HATA: Video dosyaları (book.mov veya ar_source.mov) yüklenemedi.")
    else:
        # 3. Çıktı videosu için VideoWriter'ı ayarla [cite: 89]
        frame_width = int(cap_book.get(cv2.CAP_PROP_FRAME_WIDTH))
        frame_height = int(cap_book.get(cv2.CAP_PROP_FRAME_HEIGHT))
        fps = int(cap_book.get(cv2.CAP_PROP_FPS))
        output_video_path = 'ar_dynamic_result.mp4' # [cite: 89, 98, 164]
        fourcc = cv2.VideoWriter_fourcc(*'mp4v')
        out = cv2.VideoWriter(output_video_path, fourcc, fps, (frame_width, frame_height))

        frame_count = 0

        # İpucu [cite: 102] - İşlemi hızlandırmak için kare atlama (örn: her 2 karede 1)
        # 1 = her kareyi işle, 2 = her 2 karede 1 işle
        frame_skip = 1

        print("AR video oluşturma işlemi başlıyor... Bu işlem biraz zaman alabilir[cite: 106].")

        last_good_frame = None # Titremeyi önlemek için

        while cap_book.isOpened():
            ret_book, frame_book = cap_book.read()
            if not ret_book:
                break # Kitap videosu bitti

            # Kaynak videoyu oku, biterse başa sar [cite: 86]
            ret_source, frame_source = cap_source.read()
            if not ret_source:
                cap_source.set(cv2.CAP_PROP_POS_FRAMES, 0)
                ret_source, frame_source = cap_source.read()

            frame_count += 1
            if frame_count % frame_skip != 0:
                # Atlanan kareler için son başarılı kareyi yaz (daha akıcı) [cite: 103]
                if last_good_frame is not None:
                    out.write(last_good_frame)
                else:
                    out.write(frame_book) # İlk karelerse orijinali yaz
                continue

            # 1. Kitap videosunun mevcut karesinden özellikleri çıkar [cite: 84]
            frame_book_gray = cv2.cvtColor(frame_book, cv2.COLOR_BGR2GRAY)
            kp_frame, des_frame = extract_features(frame_book_gray, 'sift')

            # 2. Kapak ile mevcut kare arasında özellikleri eşleştir [cite: 84]
            if des_frame is not None and len(des_frame) > 2:
                good_matches_ar = match_features(des_cover, des_frame, method='sift', ratio_thresh=0.75)
            else:
                good_matches_ar = []

            final_frame_to_write = frame_book.copy() # Başlangıçta orijinal kare

            # 3. Yeterli eşleşme varsa homografiyi hesapla [cite: 85]
            if len(good_matches_ar) > 10: # (min 4, ama 10 daha stabil)
                src_pts_ar = np.float32([kp_cover[m.queryIdx].pt for m in good_matches_ar]).reshape(-1, 2)
                dst_pts_ar = np.float32([kp_frame[m.trainIdx].pt for m in good_matches_ar]).reshape(-1, 2)

                # RANSAC ve Normalizasyonlu DLT'yi kullan [cite: 85]
                # (AR için daha hızlı RANSAC)
                H_ar, _, _ = compute_homography_ransac_upgraded(src_pts_ar, dst_pts_ar, iterations=500, threshold=5.0)

                if H_ar is not None:
                    # 4. Kaynak videonun karesini kitap kapağının üzerine çarpıt

                    # 'crop_center' kullanılıyor
                    frame_source_cropped = crop_center(frame_source, cover_aspect_ratio)

                    # Kırpılan görüntüyü kapağın tam boyutuna yeniden boyutlandır
                    frame_source_resized = cv2.resize(frame_source_cropped, (w_cover, h_cover))

                    # Kırpılmış ve yeniden boyutlandırılmış kareyi çarpıt [cite: 87]
                    warped_source = cv2.warpPerspective(frame_source_resized, H_ar, (frame_width, frame_height))

                    # 5. Bir maske oluşturarak sadece kitap kapağı alanını birleştir (Compositing) [cite: 88]
                    mask = np.zeros_like(frame_book, dtype=np.uint8)
                    cover_corners = np.array([[0, 0], [0, h_cover-1], [w_cover-1, h_cover-1], [w_cover-1, 0]], dtype=np.float32).reshape(-1, 1, 2)
                    transformed_corners = cv2.perspectiveTransform(cover_corners, H_ar)
                    cv2.fillPoly(mask, [np.int32(transformed_corners)], (255, 255, 255))

                    mask_inv = cv2.bitwise_not(mask)
                    book_masked = cv2.bitwise_and(final_frame_to_write, mask_inv)
                    # warped_source'u da maskeleyerek sadece ilgili alana eklenmesini garantile
                    warped_source_masked = cv2.bitwise_and(warped_source, mask)

                    final_frame_to_write = cv2.add(book_masked, warped_source_masked)
                    last_good_frame = final_frame_to_write # Son başarılı kareyi sakla

                else:
                    # Homografi bulunamazsa, son başarılı kareyi kullan
                    if last_good_frame is not None:
                        final_frame_to_write = last_good_frame

            else:
                # Eşleşme bulunamazsa, son başarılı kareyi kullan
                if last_good_frame is not None:
                    final_frame_to_write = last_good_frame

            # Çıktı karesini yaz [cite: 89]
            out.write(final_frame_to_write)

        # Her şeyi serbest bırak
        cap_book.release()
        cap_source.release()
        out.release()
        # cv2.destroyAllWindows() # Colab/Jupyter'da gereksiz

        print(f"AR videosu başarıyla '{output_video_path}' olarak kaydedildi.")